on:
  workflow_dispatch:

jobs:
  job-14:
    runs-on: macos-13
    steps:
      - run: sudo xcode-select -s /Applications/Xcode_14.3.1.app
      - run: |
          xcodebuild -downloadPlatform iOS -quiet
          open /Applications/Xcode_14.3.1.app/Contents/Developer/Applications/Simulator.app/
      - name: Open devices
        run: |
          xcodebuild -downloadPlatform iOS
          echo "[start] Open"
          open /Applications/Xcode_14.3.1.app/Contents/Developer/Applications/Simulator.app/
          echo "[done] Opened"
          echo "[start] Create"
          phone1=$(/Applications/Xcode_14.3.1.app/Contents/Developer/usr/bin/simctl create iPhone-hzso25lt6h9 com.apple.CoreSimulator.SimDeviceType.iPhone-14 com.apple.CoreSimulator.SimRuntime.iOS-16-4)
          echo "${phone1}"
          echo "[done] Created"
          echo "[start] Boot"
          boot1=$(/Applications/Xcode_14.3.1.app/Contents/Developer/usr/bin/simctl boot ${phone1})
          echo "${boot1}"
          echo "[done] Booted"
          echo "[start] Navigate"
          nav1=$(/Applications/Xcode_14.3.1.app/Contents/Developer/usr/bin/simctl openurl booted 'https://google.com') 
          echo "${nav1}"
          echo "[done] Navigated"
          
  job-15:
    runs-on: macos-13
    steps:
      - if: false
      - run: sudo xcode-select -s /Applications/Xcode_15.0.app
      - run: |
          xcodebuild -downloadPlatform iOS -quiet
          open /Applications/Xcode_15.0.app/Contents/Developer/Applications/Simulator.app/
      - name: Open devices
        run: |
          xcodebuild -downloadPlatform iOS
          echo "[start] Open"
          open /Applications/Xcode_15.0.app/Contents/Developer/Applications/Simulator.app/
          echo "[done] Opened"
          echo "[start] Create"
          phone2=$(/Applications/Xcode_15.0.app/Contents/Developer/usr/bin/simctl create iPhone-sios1839ti com.apple.CoreSimulator.SimDeviceType.iPhone-14 com.apple.CoreSimulator.SimRuntime.iOS-17-0)
          echo "${phone2}"
          echo "[done] Created"
          echo "[start] Boot"
          boot2=$(/Applications/Xcode_15.0.app/Contents/Developer/usr/bin/simctl boot ${phone2})
          echo "${boot2}"
          echo "[done] Booted"
          echo "[start] Configure Debug Logs"
          debug2=(/Applications/Xcode_15.0.app/Contents/Developer/usr/bin/simctl spawn booted log stream — level=debug)
          echo "${debug2}"
          echo "[done] Configured Debug Logs"
          echo "[start] Navigate"
          nav2=$(/Applications/Xcode_15.0.app/Contents/Developer/usr/bin/simctl openurl booted 'https://google.com')
          echo "${nav2}"
          echo "[done] Navigated"
          
  job-exp:
    runs-on: macos-13
    steps:
      - if: false
      - run: sudo xcode-select -s /Applications/Xcode_15.0.app
      - run: |
          xcodebuild -downloadPlatform iOS
          echo "[start] Open"
          open /Applications/Xcode_15.0.app/Contents/Developer/Applications/Simulator.app/
          echo "[done] Opened"
          echo "[start] Create"
          phone2=$(xcrun simctl create iPhone-sios1839ti com.apple.CoreSimulator.SimDeviceType.iPhone-14 com.apple.CoreSimulator.SimRuntime.iOS-17-0)
          echo "${phone2}"
          echo "[done] Created"
          echo "[start] Boot"
          boot2=$(xcrun simctl boot ${phone2})
          echo "${boot2}"
          echo "[done] Booted"
          echo "[start] Navigate"
          nav2=$(xcrun simctl openurl booted 'https://google.com')
          echo "${nav2}"
          echo "[done] Navigated"
        
            
#          xcodebuild -downloadPlatform iOS
#          open /Applications/Xcode_14.3.1.app/Contents/Developer/Applications/Simulator.app/
#          phone1=$(/Applications/Xcode_14.3.1.app/Contents/Developer/usr/bin/simctl create iPhone-hzso25lt6h9 com.apple.CoreSimulator.SimDeviceType.iPhone-14 com.apple.CoreSimulator.SimRuntime.iOS-16-4)
#          echo "${phone1}"
#          boot1=$(/Applications/Xcode_14.3.1.app/Contents/Developer/usr/bin/simctl boot ${phone1})
#          echo "${boot1}"
#          nav1=$(/Applications/Xcode_14.3.1.app/Contents/Developer/usr/bin/simctl openurl booted 'https://google.com') 
#          echo "${nav1}"
#          open /Applications/Xcode_15.0.app/Contents/Developer/Applications/Simulator.app/
#          phone2=$(/Applications/Xcode_15.0.app/Contents/Developer/usr/bin/simctl create iPhone-sios1839ti com.apple.CoreSimulator.SimDeviceType.iPhone-14 com.apple.CoreSimulator.SimRuntime.iOS-17-0)
#          echo "${phone2}"
#          boot2=$(/Applications/Xcode_15.0.app/Contents/Developer/usr/bin/simctl boot ${phone2})
#          echo "${boot2}"
#          nav2=$(/Applications/Xcode_15.0.app/Contents/Developer/usr/bin/simctl openurl ${phone2} 'https://google.com')
#          echo "${nav2}"
