on:
  #push:
  #pull_request:
  workflow_dispatch:

jobs:
  job-12:
    runs-on: macos-12
    steps:
      - name: Open devices
        run: |
          xcodebuild -downloadPlatform iOS open /Applications/Xcode_14.3.1.app/Contents/Developer/Applications/Simulator.app/
          phone1=$(/Applications/Xcode_14.3.1.app/Contents/Developer/usr/bin/simctl create iPhone-hzso25lt6h9 com.apple.CoreSimulator.SimDeviceType.iPhone-14 com.apple.CoreSimulator.SimRuntime.iOS-16-4)
          echo "${phone1}"
          boot1=$(/Applications/Xcode_14.3.1.app/Contents/Developer/usr/bin/simctl boot ${phone1})
          echo "${boot1}"
          nav1=$(/Applications/Xcode_14.3.1.app/Contents/Developer/usr/bin/simctl openurl booted 'https://google.com') 
          echo "${nav1}"
          open /Applications/Xcode_15.0.app/Contents/Developer/Applications/Simulator.app/
          phone2=$(/Applications/Xcode_15.0.app/Contents/Developer/usr/bin/simctl create iPhone-sios1839ti com.apple.CoreSimulator.SimDeviceType.iPhone-14 com.apple.CoreSimulator.SimRuntime.iOS-17-0)
          echo "${phone2}"
          boot2=$(/Applications/Xcode_15.0.app/Contents/Developer/usr/bin/simctl boot ${phone2})
          echo "${boot2}"
          nav2=$(/Applications/Xcode_15.0.app/Contents/Developer/usr/bin/simctl openurl ${phone2} 'https://google.com')
          echo "${nav2}"
          
  job-13:
    runs-on: macos-13
    steps:
      - name: Open devices
        run: |
          xcodebuild -downloadPlatform iOS open /Applications/Xcode_14.3.1.app/Contents/Developer/Applications/Simulator.app/
          phone1=$(/Applications/Xcode_14.3.1.app/Contents/Developer/usr/bin/simctl create iPhone-hzso25lt6h9 com.apple.CoreSimulator.SimDeviceType.iPhone-14 com.apple.CoreSimulator.SimRuntime.iOS-16-4)
          echo "${phone1}"
          boot1=$(/Applications/Xcode_14.3.1.app/Contents/Developer/usr/bin/simctl boot ${phone1})
          echo "${boot1}"
          nav1=$(/Applications/Xcode_14.3.1.app/Contents/Developer/usr/bin/simctl openurl booted 'https://google.com') 
          echo "${nav1}"
          open /Applications/Xcode_15.0.app/Contents/Developer/Applications/Simulator.app/
          phone2=$(/Applications/Xcode_15.0.app/Contents/Developer/usr/bin/simctl create iPhone-sios1839ti com.apple.CoreSimulator.SimDeviceType.iPhone-14 com.apple.CoreSimulator.SimRuntime.iOS-17-0)
          echo "${phone2}"
          boot2=$(/Applications/Xcode_15.0.app/Contents/Developer/usr/bin/simctl boot ${phone2})
          echo "${boot2}"
          nav2=$(/Applications/Xcode_15.0.app/Contents/Developer/usr/bin/simctl openurl ${phone2} 'https://google.com')
          echo "${nav2}"
          
